{
 "title": "Drone Tracker KPIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average City Temperatures",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (city)(avg_over_time(akka_actor_avg_city_temperature[5m]))"
    }
   ]
  },
  {
   "title": "Cities / Organization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (org)(akka_actor_num_cities)"
    }
   ]
  },
  {
   "title": "Num Drones / Org",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (org)(akka_actor_drone_count)"
    }
   ]
  },
  { "title": "Drones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Measurements: / min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, kubernetes_pod_name)(rate(akka_actor_measurements_sent[1m]))"
    }
   ]
  },
  {
   "title": "Num Drones",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(shard_shard_entity_count_value{shard_region=\"dronesim.Drone\"})"
    }
   ]
  },
  {
   "title": "Data Intervals",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(akka_actor_data_sample_interval)"
    },
    {
     "expr": "max(akka_actor_data_send_interval)"
    },
    { "expr": "max(akka_actor_op_interval)" }
   ]
  },
  {
   "title": "Actual Data Intervals",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(akka_actor_actual_op_interval{quantile=\"0.99\"})"
    },
    {
     "expr": "max(akka_actor_actual_data_sample_interval{quantile=\"0.99\"})"
    },
    {
     "expr": "max(akka_actor_actual_data_send_interval{quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Measurement Batch Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (instance, kubernetes_pod_name)(akka_actor_measurements_batch_size)"
    }
   ]
  },
  {
   "title": "Data Send Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile)(akka_actor_data_send_latency)"
    }
   ]
  },
  {
   "title": "Data Send Error Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(irate(akka_actor_data_send_errors[1m]))"
    }
   ]
  },
  { "title": "Data Processing Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DataEnrichment Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operator)(irate(akka_stream_operator_throughput{stream=\"data-enrichment\"}[1m]))"
    }
   ]
  },
  {
   "title": "SummarizeCityTemp Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operator)(irate(akka_stream_operator_throughput{stream=\"summarize-by-city\"}[1m]))"
    }
   ]
  },
  {
   "title": "SummarizeDrones Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operator)(irate(akka_stream_operator_throughput{stream=\"summarize-by-org\"}[1m]))"
    }
   ]
  },
  {
   "title": "DataEnrichment Proc Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (operator)(akka_stream_operator_processing_time_ns{stream=\"data-enrichment\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "SummarizeCityTemp Proc Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (operator)(akka_stream_operator_processing_time_ns{stream=\"summarize-by-city\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "SummarizeDronesProc Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (operator)(akka_stream_operator_processing_time_ns{stream=\"summarize-by-org\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Pipeline Terminated",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason)(irate(akka_actor_pipeline_terminated{pipeline=\"data-enrichment\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pipeline Terminated",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason)(irate(akka_actor_pipeline_terminated{pipeline=\"summarize-by-city\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pipeline Terminated",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reason)(irate(akka_actor_pipeline_terminated{pipeline=\"summarize-by-org\"}[1m]))"
    }
   ]
  },
  {
   "title": "Data Submit Errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(irate(akka_actor_data_submit_errors{stream=\"data-enrichment\"}[1m]))"
    }
   ]
  },
  {
   "title": "Data Submit Errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(irate(akka_actor_data_submit_errors{stream=\"summarize-by-city\"}[1m]))"
    }
   ]
  },
  {
   "title": "Data Submit Errors",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(irate(akka_actor_data_submit_errors{stream=\"summarize-by-org\"}[1m]))"
    }
   ]
  },
  { "title": "Http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Request Rate / min",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (request_path)(rate(akka_http_request_path_endpoint_responses[1m]))"
    }
   ]
  },
  {
   "title": "Response Rate 4xx | 5xx",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(irate(akka_http_http_server_responses_4xx[1m]))"
    },
    {
     "expr": "sum by (kubernetes_pod_name,instance)(irate(akka_http_http_server_responses_5xx[1m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(irate(akka_http_http_server_connections[1m]))"
    }
   ]
  },
  {
   "title": "Request Load Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_server,kubernetes_pod_name)(irate(akka_http_request_path_endpoint_responses{es_workload=\"drone-tracker\"}[1m]))"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "DataEnrichment Shards / Region",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(shard_region_shard_count_value{es_workload=\"drone-tracker\", shard_region=\"domain.DataEnrichmentWorker\"})"
    }
   ]
  },
  {
   "title": "SummarizeCityTemperature Shards / Region",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(shard_region_shard_count_value{es_workload=\"drone-tracker\", shard_region=\"domain.SummarizeCityTemperatureWorker\"})"
    }
   ]
  },
  {
   "title": "SummarizeDrones Shards / Region",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,instance)(shard_region_shard_count_value{es_workload=\"drone-tracker\", shard_region=\"domain.SummarizeDronesWorker\"})"
    }
   ]
  },
  {
   "title": "Phi Accrual Value",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (kubernetes_pod_name, self_node, remote_node)(remote_node_phi_accrual_value)"
    },
    {
     "expr": "min (self_node_phi_accrual_threshold_value)"
    }
   ]
  },
  {
   "title": "Drone Tracker Node Reachability",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " max by (kubernetes_pod_name,instance)(self_node_reachable_nodes{es_workload=\"drone-tracker\"})"
    }
   ]
  },
  {
   "title": "Drone Sim Node Reachability",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " max by (kubernetes_pod_name,instance)(self_node_reachable_nodes{es_workload=\"drone-sim\"})"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Drone Tracker Pod Restart Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (es_workload,pod,instance)(irate(kube_pod_container_restarts_rate{es_workload=\"drone-tracker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Drone Sim Pod Restart Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (es_workload,pod,instance)(irate(kube_pod_container_restarts_rate{es_workload=\"drone-sim\"}[1m]))"
    }
   ]
  }
 ]
}